import { z } from 'zod';

export const productSchema = z.object({
  name: z.string().min(1, 'Product name is required'),
  slug: z.string().optional(),
  description: z.string().min(1, 'Description is required'),
  category: z.string().min(1, 'Category is required'),
  sub_category: z.string().nullable().optional(),
  brand: z.string().min(1, 'Brand is required'),
  model: z.string().nullable().optional(),
  price: z.number().positive('Price must be positive'),
  original_price: z.number().positive().nullable().optional(),
  stock: z.number().int().min(0, 'Stock cannot be negative'),
  sku: z.string().nullable().optional(),
  warranty: z.string().nullable().optional(),
  condition: z.enum(['new', 'refurbished', 'used']).default('new'),
  tags: z.array(z.string()).optional(),
  processor: z.string().nullable().optional(),
  ram: z.string().nullable().optional(),
  storage: z.string().nullable().optional(),
  storage_type: z.string().nullable().optional(),
  graphics: z.string().nullable().optional(),
  screen_size: z.string().nullable().optional(),
  os: z.string().nullable().optional(),
  camera: z.string().nullable().optional(),
  battery: z.string().nullable().optional(),
  color: z.string().nullable().optional(),
  weight: z.string().nullable().optional(),
  dimensions: z.string().nullable().optional(),
  connectivity: z.string().nullable().optional(),
  additional_specs: z.record(z.any()).nullable().optional(),
  images: z.array(z.string()).min(1, 'At least one image is required'),
  status: z.enum(['active', 'inactive']).default('active'),
});

export type ProductInput = z.infer<typeof productSchema>;